-- Run this once in your Supabase project's SQL Editor.
create table if not exists public.sales_orders (
  id uuid primary key,
  order_number bigint generated by default as identity unique,
  terminal_id text not null,
  local_order_number integer not null,
  completed_at timestamptz not null default now(),
  items jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.sales_orders enable row level security;

-- Festival POS devices may insert orders and read the combined report.
-- Updates are allowed only for the same order UUID, which makes retries idempotent.
create policy "festival devices insert sales"
on public.sales_orders for insert to anon with check (true);

create policy "festival devices read report"
on public.sales_orders for select to anon using (true);

create policy "festival devices update queued sale"
on public.sales_orders for update to anon using (true) with check (true);

create index if not exists sales_orders_completed_at_idx
on public.sales_orders (completed_at desc);
