-- Run this once in your Supabase project's SQL Editor.
create table if not exists public.sales_orders (
  id uuid primary key,
  order_number bigint generated by default as identity unique,
  terminal_id text not null,
  local_order_number integer not null,
  event_day date not null default ((now() at time zone 'Asia/Beirut')::date),
  completed_at timestamptz not null default now(),
  items jsonb not null,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

-- Safe migration for databases created before event-day separation.
-- Existing festival invoices belong to Saturday, 12 September 2026.
alter table public.sales_orders add column if not exists event_day date;
update public.sales_orders set event_day = date '2026-09-12' where event_day is null;
alter table public.sales_orders alter column event_day set default ((now() at time zone 'Asia/Beirut')::date);
alter table public.sales_orders alter column event_day set not null;

-- Soft-deleted invoices remain available for review, but are excluded from reports.
alter table public.sales_orders add column if not exists deleted_at timestamptz;

alter table public.sales_orders enable row level security;

-- Festival POS devices may insert orders and read the combined report.
-- Updates are allowed only for the same order UUID, which makes retries idempotent.
create policy "festival devices insert sales"
on public.sales_orders for insert to anon with check (true);

create policy "festival devices read report"
on public.sales_orders for select to anon using (true);

create policy "festival devices update queued sale"
on public.sales_orders for update to anon using (true) with check (true);

create index if not exists sales_orders_completed_at_idx
on public.sales_orders (completed_at desc);

create index if not exists sales_orders_event_day_idx
on public.sales_orders (event_day);
